### ISSUE TITLE
Update googleapis to latest

### ISSUE THREAD

**Issue by ardittristan** [sammachin/node-red-contrib-google-sheets#10]
Looking at the changelog since v46 no breaking changes occurred in the JWS auth/google sheets part of the package. Only new api features and vulnerability patches have been added.

It would be awesome to see googleapis updated to the latest version!

**Comment by sammachin** [comment]
bumped in 1.0.0 to 86, however keeping up with the releases is not going to be an easy task as google increase the major verison regularly
