### ISSUE TITLE
Last cell in column

### ISSUE THREAD

**Issue by frank-nobrega** [sammachin/node-red-contrib-google-sheets#11]
Is it possible to retrieve the value of the last non blank cell in a column?  The spreadsheet I want to use has new rows added as new data comes in so I don't always know the row number. Google Sheets uses the INDEX function to do this but I couldn't get that to work with your node.

**Comment by sammachin** [comment]
Hi @frank-nobrega 

You can fetch an entire column by  specifying that in the Cells query, for example to fetch Column A of Sheet1 use `Sheet1!A:A`
If you also check the `Flatten Matrix` box this will then return that whole column as an array in `msg.payload`
You can then access the last item in the array using a change node with the `expression` option and the value of `payload[-1]`
See below pics for the node config

https://cdn.zappy.app/a897f4c73f1ce51b5dfe3d5a2e917480.png
https://cdn.zappy.app/7c2cff4cf461a52c238388fb0e647435.png
