### ISSUE TITLE
Why not use msg.cells to set the value for the cells input for this node rather than use msg.topic?

### ISSUE THREAD

**Issue by bigdoods** [sammachin/node-red-contrib-google-sheets#13]
Firstly, thank you for the awesome node! 

As the title says. Is there a reason this pattern was not used? I am now dynamically using this node and setting my input to:

msg.sheet = "url of sheet"
msg.topic = "value for cells"

I would prefer if I was doing:

msg.sheet = "url of sheet"
msg.cells = "value for cells" (_note msg.cells_)

https://github.com/sammachin/node-red-contrib-google-sheets/blob/38cb29796ca8c03593856a5c9c68fa7a26f25163/gsheet.js#L17

**Comment by sammachin** [comment]
Hey John, yes that would make a lot more sense. I can't remember any strong reason I used topic, I think the first version didn't use msg.sheet it was just in the config so the only inputs were topic & payload. 

It's an easy enough change to make, I just need to think about either making it as a breaking change or if I can use msg.cells and fallback to msg.topic.

**Comment by sammachin** [comment]
This is now changed in 1.0.0 it will fallback to msg.topic for now just in case I break anything but msg.cells is the preferred place now.

**Comment by bigdoods** [comment]
Thanks Sam.
