### ISSUE TITLE
Get old Data's

### ISSUE THREAD

**Issue by pyrler** [sammachin/node-red-contrib-google-sheets#14]
Hello
I want to read data from my spreadsheet.  so far that works too.  
If I change the data in the spreadsheet, I still get the old data in Node-Red.  Know not the current ones?  
The spreadsheet cells are calculated cells which are updated cyclically (= GOOGLEFINANCE ()).  Please help why no current values ​​come back.  thanks

**Comment by sammachin** [comment]
Can you privode an example sheet and flow that demonstrates the issue, I've done some basic tests with a sheet using GOOGLEFINANCE in cells and it seems to update fine even with the sheet closed.

**Comment by pyrler** [comment]
Link to a copy of the Sheet. i Deleted a few data because its my personal investments..
https://docs.google.com/spreadsheets/d/1OZFW83JToatLIw3jznuxkS9gXkgIkj90Ys1Gl2OPQ_0/edit

i have it run now a few days and it work sometimes better sometimes worse..

i can defined when its better or worse. sometimes the data is from yesterday and sometime tha data is actual.. for me not logical.. 
i have made somthine else with ifttt that works pretty good for a few weeks. i want to move the logic away from ifttt to my node-red..

thanks for your help..
let me know if you need more..

**Comment by sammachin** [comment]
What is your node-red flow trying to do

**Comment by pyrler** [comment]
The Flow is getting Data all minute from cell: Details!D3:D10 (Node 1)
Details !A13:T40 (Node2)

Its difficult to test on weekend because the stock exchange is closed and the data doesnt change..

**Comment by sammachin** [comment]
This seems odd, as its an intermittent issue I can only think that there is something in the google sheets side that doesn't always update a sheet with googlefinance calls if it is not open, perhaps Google are putting the sheet to sleep in the background somehow.

The node-red package is just a simple wrapper around the https://www.npmjs.com/package/googleapis sheets calls, the fact that its not returning an error rather its returning old data says to me its on the google side.

I found this article about getting Google Sheets to update the finance calls in the background with Geckoboard whcih seems realted. https://support.geckoboard.com/hc/en-us/articles/207337458-Use-Google-Sheets-GoogleFinance-function-to-display-data-in-Geckoboard-

**Comment by pyrler** [comment]
With this lib, I also don't always have up-to-date data when I have the sheet open on the notebook. (Or iPad). That's why I don't necessarily assume a Google error...?

The goal was to integrate sheets into Node-RED because I already use this. So that I can replace IFTTT. If I use another portal now, it won't help. With IFTTT, the update also works with the sheet closed for days.

Do you have any other idea to try in Node-RED?

**Comment by sammachin** [comment]
Can you share your node-red flow, I can't seem to reproduce this with a simple inject node reading from the sheet I'm wondering if you're doing something else in your flow thats returning the stale data?

I've also just updated the pacakge to 1.1.0 the only change is to update the dependency to the latest version of googleapis, I can't see any specific changes in there relating to the sheets API and finance but its worth a try.

**Comment by pyrler** [comment]
Here my Flow:

`[
    {
        "id": "147f348558b5b45f",
        "type": "fp-button",
        "z": "ea45deff30b0610d",
        "value": "true",
        "valueType": "bool",
        "buildingClk": "",
        "categoryClk": "",
        "pageClk": "",
        "roomClk": "",
        "valueDbl": "true",
        "valueTypeDbl": "bool",
        "buildingDbl": "",
        "categoryDbl": "",
        "pageDbl": "",
        "roomDbl": "",
        "valueLong": "true",
        "valueTypeLong": "bool",
        "buildingLong": "",
        "categoryLong": "",
        "pageLong": "",
        "roomLong": "",
        "valuePush": "true",
        "valueTypePush": "bool",
        "valueRelease": "false",
        "valueTypeRelease": "bool",
        "outputs": 4,
        "outputDefaultLabels": [
            "alle",
            "klick",
            "doppelklick",
            "langer klick"
        ],
        "name": "",
        "template": "custom",
        "mapping": "room",
        "building": "43ac6417.dc970c",
        "category": "ebcfb3de48629843",
        "page": "a96b2c6c.c1e54",
        "room": "8fafe9f4.dcf158",
        "container": "",
        "description": "Update",
        "position": "8",
        "pos_x": "0",
        "pos_y": "0",
        "width": "50",
        "height": "50",
        "enable_plan": false,
        "enable_mobile": false,
        "enable_zone": true,
        "enable_central": false,
        "topic0": "",
        "topic1": "",
        "topic2": "",
        "topic3": "",
        "icon": "automatik",
        "icon_color": "#404040",
        "label_txt": "",
        "label_color": "#404040",
        "label_style": "normal",
        "label_size": "0",
        "label_align": "center",
        "label_valign": "top",
        "icon_rotation": "0",
        "options": [],
        "status_mode": "none",
        "variant": "click",
        "rights-0": 1632778083835,
        "x": 60,
        "y": 260,
        "wires": [
            [],
            [
                "2ab2f79739b1d5b1",
                "076725f24d9918ef"
            ],
            [],
            []
        ]
    },
    {
        "id": "43ac6417.dc970c",
        "type": "fp-building-config",
        "building": "lein",
        "name": "Lein 2",
        "position": "0"
    },
    {
        "id": "ebcfb3de48629843",
        "type": "category-config",
        "category": "finanzen",
        "name": "Finanzen",
        "icon": "rechts-rauf",
        "background": "#404040",
        "position": "4"
    },
    {
        "id": "a96b2c6c.c1e54",
        "type": "page-config",
        "page": "zentral",
        "name": "Zentral",
        "short_name": "Zentral",
        "page_type": "page",
        "image": "none.png",
        "image_rotation": "0",
        "image_mirror": "none",
        "pos_x": "0",
        "pos_y": "0",
        "width": "0",
        "height": "0",
        "background": "#ffffff",
        "position": "0",
        "max_width": "1024",
        "max_height": "660",
        "hidden": "single",
        "autoscale": true,
        "zone_open": false,
        "zone_close_on_click_outside": true
    },
    {
        "id": "8fafe9f4.dcf158",
        "type": "fp-room-config",
        "room": "zentral",
        "name": "Zentral",
        "icon": "szene.svg",
        "position": "0"
    }
] ` 


I have updated now.. will see..

**Comment by sammachin** [comment]
The flow you shared doesn’t have any Google sheets nodes in it, did you
export the whole thing?
Also what are the other custom nodes you are using?

**Comment by pyrler** [comment]
i think, this is the right one.. sorry
the other nodes are a private contrib library of my company.. some nodes for a building automation visualisation..

`[
    {
        "id": "ea45deff30b0610d",
        "type": "tab",
        "label": "Google Sheets",
        "disabled": false,
        "info": ""
    },
    {
        "id": "7f7ecd95bf744988",
        "type": "inject",
        "z": "ea45deff30b0610d",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "*/30 8-22 * * 1,2,3,4,5",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 80,
        "y": 160,
        "wires": [
            [
                "2ab2f79739b1d5b1",
                "076725f24d9918ef"
            ]
        ]
    },
    {
        "id": "2ab2f79739b1d5b1",
        "type": "GSheet",
        "z": "ea45deff30b0610d",
        "creds": "519682ef9eec088d",
        "method": "get",
        "action": "",
        "sheet": "1-0Nu_e7x00ndoFTBMrO0IO6VIopoMkBBIQ-UFFEatrQ",
        "cells": "Übersicht!A12:T40",
        "flatten": false,
        "name": "Unternehmensdaten",
        "x": 310,
        "y": 160,
        "wires": [
            [
                "8d20d9dfff0c4ea0",
                "dbb931467a1bed8f"
            ]
        ]
    },
    {
        "id": "076725f24d9918ef",
        "type": "GSheet",
        "z": "ea45deff30b0610d",
        "creds": "519682ef9eec088d",
        "method": "get",
        "action": "",
        "sheet": "1-0Nu_e7x00ndoFTBMrO0IO6VIopoMkBBIQ-UFFEatrQ",
        "cells": "Übersicht!D3:D10",
        "flatten": true,
        "name": "Zusammenfassung",
        "x": 300,
        "y": 220,
        "wires": [
            [
                "b217d8a5cabd0464",
                "9ad24784c3997adf",
                "c5f30d0b24ab2c88",
                "d3579f2cbe50c694",
                "e8857d2c27cd03f7",
                "cdb70ba5a6719d47"
            ]
        ]
    },
    {
        "id": "b217d8a5cabd0464",
        "type": "debug",
        "z": "ea45deff30b0610d",
        "name": "Aktien Zusammenfassung",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 540,
        "y": 220,
        "wires": []
    },
    {
        "id": "9ad24784c3997adf",
        "type": "change",
        "z": "ea45deff30b0610d",
        "name": "",
        "rules": [
            {
                "t": "move",
                "p": "payload[0]",
                "pt": "msg",
                "to": "payload",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 540,
        "y": 270,
        "wires": [
            [
                "fc0310df1e3814f8"
            ]
        ]
    },
    {
        "id": "c5f30d0b24ab2c88",
        "type": "change",
        "z": "ea45deff30b0610d",
        "name": "",
        "rules": [
            {
                "t": "move",
                "p": "payload[4]",
                "pt": "msg",
                "to": "payload",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 540,
        "y": 330,
        "wires": [
            [
                "920f5d6b72dc3b99"
            ]
        ]
    },
    {
        "id": "d3579f2cbe50c694",
        "type": "change",
        "z": "ea45deff30b0610d",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "finanzen.heute",
                "pt": "global",
                "to": "payload[5]",
                "tot": "msg"
            },
            {
                "t": "move",
                "p": "payload[5]",
                "pt": "msg",
                "to": "payload",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 520,
        "y": 390,
        "wires": [
            [
                "8d5f5bd3922d041e"
            ]
        ]
    },
    {
        "id": "e8857d2c27cd03f7",
        "type": "change",
        "z": "ea45deff30b0610d",
        "name": "",
        "rules": [
            {
                "t": "move",
                "p": "payload[6]",
                "pt": "msg",
                "to": "payload",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 540,
        "y": 450,
        "wires": [
            [
                "64fee3d2ea94f4af"
            ]
        ]
    },
    {
        "id": "cdb70ba5a6719d47",
        "type": "change",
        "z": "ea45deff30b0610d",
        "name": "",
        "rules": [
            {
                "t": "move",
                "p": "payload[7]",
                "pt": "msg",
                "to": "payload",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 540,
        "y": 510,
        "wires": [
            [
                "fa7b58b043508170"
            ]
        ]
    },
    {
        "id": "fc0310df1e3814f8",
        "type": "fp-text",
        "z": "ea45deff30b0610d",
        "label_txt": "",
        "label_suffix": "",
        "label_prefix": "",
        "label_color": "#404040",
        "label_style": "normal",
        "label_size": 16,
        "label_align": "center",
        "label_valign": "middle",
        "background": "#ffffff",
        "decimal_places": 1,
        "persistState": true,
        "name": "Depotwert",
        "mapping": "room",
        "building": "43ac6417.dc970c",
        "category": "ebcfb3de48629843",
        "page": "a96b2c6c.c1e54",
        "room": "8fafe9f4.dcf158",
        "container": "",
        "description": "",
        "position": "0",
        "pos_x": "0",
        "pos_y": "0",
        "width": "50",
        "height": "50",
        "enable_plan": false,
        "enable_mobile": false,
        "enable_zone": true,
        "enable_central": true,
        "rights-0": 1633548038546,
        "x": 770,
        "y": 270,
        "wires": []
    },
    {
        "id": "920f5d6b72dc3b99",
        "type": "fp-text",
        "z": "ea45deff30b0610d",
        "label_txt": "",
        "label_suffix": "",
        "label_prefix": "",
        "label_color": "#404040",
        "label_style": "normal",
        "label_size": 16,
        "label_align": "center",
        "label_valign": "middle",
        "background": "#ffffff",
        "decimal_places": "",
        "persistState": true,
        "name": "G/V Total",
        "mapping": "room",
        "building": "43ac6417.dc970c",
        "category": "ebcfb3de48629843",
        "page": "a96b2c6c.c1e54",
        "room": "8fafe9f4.dcf158",
        "container": "",
        "description": "",
        "position": "1",
        "pos_x": "0",
        "pos_y": "0",
        "width": "50",
        "height": "50",
        "enable_plan": false,
        "enable_mobile": false,
        "enable_zone": true,
        "enable_central": true,
        "rights-0": 1633548044783,
        "x": 760,
        "y": 330,
        "wires": []
    },
    {
        "id": "8d5f5bd3922d041e",
        "type": "fp-text",
        "z": "ea45deff30b0610d",
        "label_txt": "",
        "label_suffix": "",
        "label_prefix": "",
        "label_color": "#404040",
        "label_style": "normal",
        "label_size": 16,
        "label_align": "center",
        "label_valign": "middle",
        "background": "#ffffff",
        "decimal_places": "",
        "persistState": true,
        "name": "G/V Heute",
        "mapping": "room",
        "building": "43ac6417.dc970c",
        "category": "ebcfb3de48629843",
        "page": "a96b2c6c.c1e54",
        "room": "8fafe9f4.dcf158",
        "container": "",
        "description": "",
        "position": "2",
        "pos_x": "0",
        "pos_y": "0",
        "width": "50",
        "height": "50",
        "enable_plan": false,
        "enable_mobile": false,
        "enable_zone": true,
        "enable_central": true,
        "rights-0": 1633548050267,
        "x": 770,
        "y": 390,
        "wires": []
    },
    {
        "id": "922898b378ba0313",
        "type": "hb-func-alarm-transmission",
        "z": "ea45deff30b0610d",
        "mail": "",
        "phone": "",
        "subject": "Update",
        "text": "",
        "user": "Kevin",
        "http_config": "661a6602.f5fb48",
        "interfaces": "default",
        "name": "",
        "notification_type": "push",
        "topic0": "msg",
        "topic1": "error",
        "topic2": "error",
        "x": 790,
        "y": 610,
        "wires": [
            [],
            [],
            []
        ]
    },
    {
        "id": "3d6759cdb80f917a",
        "type": "inject",
        "z": "ea45deff30b0610d",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "20 09 * * 1,2,3,4,5",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 400,
        "y": 610,
        "wires": [
            [
                "246f9b1bb837d236"
            ]
        ]
    },
    {
        "id": "3b1df7a6054c02f1",
        "type": "inject",
        "z": "ea45deff30b0610d",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "00 12 * * 1,2,3,4,5",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 400,
        "y": 660,
        "wires": [
            [
                "246f9b1bb837d236"
            ]
        ]
    },
    {
        "id": "3b51c8edac561ad9",
        "type": "inject",
        "z": "ea45deff30b0610d",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "00 15 * * 1,2,3,4,5",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 400,
        "y": 710,
        "wires": [
            [
                "246f9b1bb837d236"
            ]
        ]
    },
    {
        "id": "fbfcdd5ba9ed0cbf",
        "type": "inject",
        "z": "ea45deff30b0610d",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "00 18 * * 1,2,3,4,5",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 400,
        "y": 760,
        "wires": [
            [
                "246f9b1bb837d236"
            ]
        ]
    },
    {
        "id": "fd224c6081fdb359",
        "type": "inject",
        "z": "ea45deff30b0610d",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "00 22 * * 1,2,3,4,5",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 400,
        "y": 810,
        "wires": [
            [
                "246f9b1bb837d236"
            ]
        ]
    },
    {
        "id": "8d20d9dfff0c4ea0",
        "type": "debug",
        "z": "ea45deff30b0610d",
        "name": "",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 510,
        "y": 70,
        "wires": []
    },
    {
        "id": "dbb931467a1bed8f",
        "type": "function",
        "z": "ea45deff30b0610d",
        "name": "",
        "func": "const GewuenschteZellen = [0,3,7,17]\nlet input = msg.payload;\nlet header = [];\nlet rows = [];\n\nfor (let i = 0; i < input.length; i++) {\n    let newInput = [];\n    for (let x = 0; x < input[0].length; x++) {\n       if (GewuenschteZellen.includes(x)) {\n           newInput.push(input[i][x])\n       }\n  }   \n  rows.push(newInput);\n}\n\nheader = rows.shift();\nnode.send({payload:{headers:header,rows}});",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 490,
        "y": 160,
        "wires": [
            [
                "af139315dbe4a3d4"
            ]
        ]
    },
    {
        "id": "af139315dbe4a3d4",
        "type": "fp-table",
        "z": "ea45deff30b0610d",
        "name": "",
        "mapping": "room",
        "building": "43ac6417.dc970c",
        "category": "ebcfb3de48629843",
        "page": "a96b2c6c.c1e54",
        "room": "8fafe9f4.dcf158",
        "container": "",
        "description": "Depot",
        "position": "49",
        "pos_x": "0",
        "pos_y": "0",
        "width": "50",
        "height": "50",
        "enable_plan": false,
        "enable_mobile": true,
        "enable_zone": false,
        "enable_central": false,
        "view": "page-1",
        "icon": "archiv",
        "color": "#404040",
        "label_txt": "",
        "color_label": "#404040",
        "label_style": "normal",
        "label_size": "0",
        "label_align": "center",
        "label_valign": "top",
        "icon_rotation": "0",
        "rights-0": 1633000040625,
        "x": 770,
        "y": 160,
        "wires": []
    },
    {
        "id": "246f9b1bb837d236",
        "type": "function",
        "z": "ea45deff30b0610d",
        "name": "",
        "func": "const url = \"/?type=page&mode=category&view=list&building=lein&category=finanzen&page=zentral\";\nconst text = global.get(\"finanzen.heute\");\nnode.send({payload:true,text,url});",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 570,
        "y": 610,
        "wires": [
            [
                "922898b378ba0313"
            ]
        ]
    },
    {
        "id": "147f348558b5b45f",
        "type": "fp-button",
        "z": "ea45deff30b0610d",
        "value": "true",
        "valueType": "bool",
        "buildingClk": "",
        "categoryClk": "",
        "pageClk": "",
        "roomClk": "",
        "valueDbl": "true",
        "valueTypeDbl": "bool",
        "buildingDbl": "",
        "categoryDbl": "",
        "pageDbl": "",
        "roomDbl": "",
        "valueLong": "true",
        "valueTypeLong": "bool",
        "buildingLong": "",
        "categoryLong": "",
        "pageLong": "",
        "roomLong": "",
        "valuePush": "true",
        "valueTypePush": "bool",
        "valueRelease": "false",
        "valueTypeRelease": "bool",
        "outputs": 4,
        "outputDefaultLabels": [
            "alle",
            "klick",
            "doppelklick",
            "langer klick"
        ],
        "name": "",
        "template": "custom",
        "mapping": "room",
        "building": "43ac6417.dc970c",
        "category": "ebcfb3de48629843",
        "page": "a96b2c6c.c1e54",
        "room": "8fafe9f4.dcf158",
        "container": "",
        "description": "Update",
        "position": "8",
        "pos_x": "0",
        "pos_y": "0",
        "width": "50",
        "height": "50",
        "enable_plan": false,
        "enable_mobile": false,
        "enable_zone": true,
        "enable_central": false,
        "topic0": "",
        "topic1": "",
        "topic2": "",
        "topic3": "",
        "icon": "automatik",
        "icon_color": "#404040",
        "label_txt": "",
        "label_color": "#404040",
        "label_style": "normal",
        "label_size": "0",
        "label_align": "center",
        "label_valign": "top",
        "icon_rotation": "0",
        "options": [],
        "status_mode": "none",
        "variant": "click",
        "rights-0": 1632778083835,
        "x": 60,
        "y": 260,
        "wires": [
            [],
            [
                "2ab2f79739b1d5b1",
                "076725f24d9918ef"
            ],
            [],
            []
        ]
    },
    {
        "id": "64fee3d2ea94f4af",
        "type": "fp-text",
        "z": "ea45deff30b0610d",
        "label_txt": "",
        "label_suffix": "",
        "label_prefix": "",
        "label_color": "#404040",
        "label_style": "normal",
        "label_size": 16,
        "label_align": "center",
        "label_valign": "middle",
        "background": "#ffffff",
        "decimal_places": "",
        "persistState": true,
        "name": "Rendite p.A.",
        "mapping": "room",
        "building": "43ac6417.dc970c",
        "category": "ebcfb3de48629843",
        "page": "a96b2c6c.c1e54",
        "room": "8fafe9f4.dcf158",
        "container": "",
        "description": "Rendite p.A. seit 01.01.2019",
        "position": "3",
        "pos_x": "0",
        "pos_y": "0",
        "width": "50",
        "height": "50",
        "enable_plan": false,
        "enable_mobile": false,
        "enable_zone": true,
        "enable_central": true,
        "rights-0": 1633548055746,
        "x": 770,
        "y": 450,
        "wires": []
    },
    {
        "id": "fa7b58b043508170",
        "type": "fp-text",
        "z": "ea45deff30b0610d",
        "label_txt": "",
        "label_suffix": "",
        "label_prefix": "",
        "label_color": "#404040",
        "label_style": "normal",
        "label_size": 16,
        "label_align": "center",
        "label_valign": "middle",
        "background": "#ffffff",
        "decimal_places": "",
        "persistState": true,
        "name": "Dividenden",
        "mapping": "room",
        "building": "43ac6417.dc970c",
        "category": "ebcfb3de48629843",
        "page": "a96b2c6c.c1e54",
        "room": "8fafe9f4.dcf158",
        "container": "",
        "description": "",
        "position": "4",
        "pos_x": "0",
        "pos_y": "0",
        "width": "50",
        "height": "50",
        "enable_plan": false,
        "enable_mobile": false,
        "enable_zone": true,
        "enable_central": true,
        "rights-0": 1633548061944,
        "x": 770,
        "y": 510,
        "wires": []
    },
    {
        "id": "519682ef9eec088d",
        "type": "gauth"
    },
    {
        "id": "43ac6417.dc970c",
        "type": "fp-building-config",
        "building": "lein",
        "name": "Lein 2",
        "position": "0"
    },
    {
        "id": "ebcfb3de48629843",
        "type": "category-config",
        "category": "finanzen",
        "name": "Finanzen",
        "icon": "rechts-rauf",
        "background": "#404040",
        "position": "4"
    },
    {
        "id": "a96b2c6c.c1e54",
        "type": "page-config",
        "page": "zentral",
        "name": "Zentral",
        "short_name": "Zentral",
        "page_type": "page",
        "image": "none.png",
        "image_rotation": "0",
        "image_mirror": "none",
        "pos_x": "0",
        "pos_y": "0",
        "width": "0",
        "height": "0",
        "background": "#ffffff",
        "position": "0",
        "max_width": "1024",
        "max_height": "660",
        "hidden": "single",
        "autoscale": true,
        "zone_open": false,
        "zone_close_on_click_outside": true
    },
    {
        "id": "8fafe9f4.dcf158",
        "type": "fp-room-config",
        "room": "zentral",
        "name": "Zentral",
        "icon": "szene.svg",
        "position": "0"
    },
    {
        "id": "661a6602.f5fb48",
        "type": "hb-http-config",
        "name": "",
        "proxy_enabled": false,
        "interfaces": []
    }
] `

**Comment by pyrler** [comment]
i think, its ok now. the only thing i made is raise the interval… it works for me now
thanks for your support
