### ISSUE TITLE
Example on how to log temperatures allows setting a timestamp on adjacent column 

### ISSUE THREAD

**Issue by feedrate** [sammachin/node-red-contrib-google-sheets#24]
Got it sending data fairly easily to G-sheets and many thanks for that.
But I'm having a hard time logging individual temp values and at the same time enabling using scripts in sheets to set a time stamp on the column next to the cell that stores the value from node red.

This might be related to me not understanding this properly!
Perhaps I've set it up wrong, but for me to log (in a column) every registered value, I have to first "Append Row"  followed by a "Update Cells"
![image](https://user-images.githubusercontent.com/30080737/188718805-19d0ccbf-c681-4847-acab-c5047015f1d3.png)

But this leaves me unable to:
1. setup a function in the sheet itself (because a new blank row is created no longer containing the function) 
2. using a functional Apps Script to update the adjacent column, this works for all entries **I** make, but for some reason not for the ones that are sent from Node-red.

Any help is greatly appreciated.

Cheers,
K

**Comment by feedrate** [comment]
Also tried this:
![image](https://user-images.githubusercontent.com/30080737/188935408-02296398-a4eb-42c9-b426-d312ec0b11c8.png)
And this:
![image](https://user-images.githubusercontent.com/30080737/188935991-dc804d1b-ac5d-4218-9fab-130bd26803ee.png)

But it seems that it does not Append a Row in the A column and the B column for each node.
Looks like this after:
![image](https://user-images.githubusercontent.com/30080737/188936072-ffc2f47c-70ff-4f27-a9aa-12560ef7a527.png)

Does it make a new Row for all columns no matter if one specify a specific column? Perhaps that's what's happening here?

**Comment by sammachin** [comment]
Appending a row will apply to all cells in that row regardless of if they are empty or not, 
Google Sheets looks for the next row that is empty in every column.
If you want to add multiple columns in the same row you should send your data as an array eg `[21.2, "Wed Sep 07 2022 18:54"]`

**Comment by sammachin** [comment]
Also applying functions in the google sheet that you're also updating programatically is not reccomended, either keep all the logic in node-red or have a separate data sheet in your workbook and then use functions in another sheet to read and calculate from the data sheet

**Comment by feedrate** [comment]
> Appending a row will apply to all cells in that row regardless of if they are empty or not, Google Sheets looks for the next row that is empty in every column. If you want to add multiple columns in the same row you should send your data as an array eg `[21.2, "Wed Sep 07 2022 18:54"]`

Thank you - Using Join, and set to create "an Array" works as intended:
![image](https://user-images.githubusercontent.com/30080737/191849464-b642290b-5800-4ada-acfb-718221dff940.png)

This reduces my sheets by half, cheers again,.
