### ISSUE TITLE
Set cells by msg.payload

### ISSUE THREAD

**Issue by AutoTwisty** [sammachin/node-red-contrib-google-sheets#27]
Is it possible to flexibly change the "Cells" characteristic by msg.payload or some other external source? I would like to have a single GSheets node grab data from multiple different rows and columns that are being updated by other sources, so the row numbers are not stable. I already have code to find the rows and columns and pars it into the syntax GSheets node wants in the "Cells" field, but it does not seem to accept "msg.payload" or any variation thereof as a input.
Am I missing something or is this no a function of the node atm?

**Comment by sammachin** [comment]
you can specify the value for Sheet and Cells in the msg.cells property on input and leave the config in the node blank.
Its in the node help text.
