### ISSUE TITLE
Arrays are flattened

### ISSUE THREAD

**Issue by ralrom** [sammachin/node-red-contrib-google-sheets#3]
Hello,

First, thank you for developing this.

While using this node, I noticed an issue:
All arrays passed through the Get method are flattened, which makes it difficult to work with block selections (i.e.: A1:C3). It also doesn't produce the result which is documented on the node:

> If both row and colums are request msg.payload will contain nested arrays as columns eg for A1:C3 : [["A1","B1","C1"],["A2","B2","C2"],["A3","B3","C3"]]

Here's the problematic line of code:

https://github.com/sammachin/node-red-contrib-google-sheets/blob/cd02fb8f4d5fdeae43b84a74c9262e8cc7901071/gsheet.js#L46

**Comment by sammachin** [comment]
Hi, 
Yes that was kinda a conscious choice as I was often fetching columns of data and having arrays of arrays was awkwrd to work with. I'm thinking that making it an option in the node config so a check box for "flatten output" might be a compromise?

**Comment by ralrom** [comment]
An option would be good

Another way to do it would be to check the column count: for cases where we have only 1 column, we could flatten it to make it less akward to work with, and if there are 2 columns or more, return the array as is

**Comment by sammachin** [comment]
Have added an option in v0.1.0 (just released) that allows you to choose whether to flatten a matrix or not
