### ISSUE TITLE
Use of multiple sheets

### ISSUE THREAD

**Issue by andyp17** [sammachin/node-red-contrib-google-sheets#7]
Hello,
I find this not very usefull and I like to use it. But I have one question/issue. I want to use several sheets in one file (sheet1, sheet2...). But whatever which name of the sheet I send with msg.sheet, the node writes always to the first sheet. If I change the order of the sheets (in the file), always the first sheet is written.
Is there a limitation? Thanks!

KR
Andreas Posch

**Comment by sammachin** [comment]
Hi Andreas

`msg.sheet` is used to refer to the Google Sheet ID of the whole workbook not the individual tab, you can specify the tab in the Cells reference eg `Sheet1!A1:B2` or you can put that value in `msg.topic` If you don't specify a tab name separated qith a `!` it will default to the first one.

Its a bit confusing with the terminolofy, I should really talk about workbook ID I guess but I think this was inherired from the library I'm using, I'll see if I can make it any clearer on the next update.

**Comment by sammachin** [comment]
leaving this open to remind me to revist the naming

**Comment by andyp17** [comment]
Hello,
Thanks for your hint - works like a charm.. 👍 

KR
Andreas

**Comment by sammachin** [comment]
I've improved the help in 1.0.0 to hopefully avoid this confusion, Looking into it more googles naming here is inconsistent between a file(workbook) and tabs (sheets)
